### ISSUE TITLE
It failed to train with 102flowers dataset

### ISSUE THREAD

**Issue by Johnson-yue** [akanimax/BBMSG-GAN#3]
Hi, I tried BMSG-GAN with 102 flowers dataset ,and the result is very good, So I want to tried BBMSG for better result ,and I can not train it with 102 flower dataset  with default parameters.

I trained 400 epochs but generate is still:
![gen_400_18](https://user-images.githubusercontent.com/10268274/71465637-29824f80-27f8-11ea-97c1-96b55b48136d.png)

Can you check it ??

**Comment by akanimax** [comment]
@Johnson-yue, 
Hope I am not too late..
From what I see, you have either set the spoofing factor to a very large value (something like `2` or `4` works best) or you haven't trained the model long enough.
As apparent from your results, it is not failed at all. The network is learning to generate flower like blobs. I would highly encourage you to keep training this model till at least 1000 epochs and then check the results. For ablation experiment, you could try to run the same model again with a smaller spoofing factor too.

Hope this helps! 

Cheers :beers:!
@akanimax

**Comment by Johnson-yue** [comment]
@akanimax yes, you are right, I am trained this model until to 1500 epoch. And the `spoofing_factor` default is 16 and I am not change it , as your said ,it very big.

But when it finished train at 1500 epochs, it looks like better than before , but not good than BMSG-GAN, I think.

My train script is:
```
#!/usr/bin/bash
python train.py --depth=6 \
                --latent_size=512 \
                --images_dir="/home/ubuntu/media_data/public_Data/102flowers/jpg_128" \
                --sample_dir="samples/exp_flowers_1" \
                --model_dir="models/exp_flower_1" \
                --batch_size 8 \
                --num_workers 10 
```
and when training 1500 epochs, the train image is : 
![gen_1500_9](https://user-images.githubusercontent.com/10268274/71649709-dce4ca00-2d4b-11ea-94d8-4514344892f3.png)

I will decrease  `spoofing_factor=4` and try it again, Do you have any other suggestions?? 

I really appreciate your timely and patient reply, which helps me to understand your method and makes great contribution to the development of technology .For example ,**StyleGAN-v2** draws on your method, **Great Job!!!!**

**Comment by akanimax** [comment]
@Johnson-yue,
Indeed, the `spoofing_factor=16` is a very high value. I think I should change the default value altogether. 
Thanks a lot for you compliment :smile:! It means a lot for me. 
Yeah true, the nvidia's stylegan2 citation has been a very big surprise for me. I am glad that the researchers at Nvidia considered my work and the multi-scale gradients improved the results.
Please let me know if you have any further questions. I'll try to answer them as promptly as possible. 

Best regards,
@akanimax
